version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "18083:18083"
      - "2096:18084"
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8443:8084"
      - "8001:5000"
    volumes:
      - .:/app
      - ./mqtt/emqx.conf:/etc/emqx/emqx.conf
      - ./nginx/nginx.conf:/etc/nginx/sites-available/nginx.conf
      - ./certs/:/etc/ssl/eoh-certs/
      - ./datadog/datadog.yaml:/etc/datadog-agent/datadog.yaml
      - ./datadog/logs.yaml:/etc/datadog-agent/conf.d/logs.d/conf.yaml
      - emqx_data:/usr/lib/emqx/data
      - emqx_log:/var/log/emqx
      - uwsgi_log:/var/log/uwsgi
      - nginx_log:/var/log/nginx
      - supervisor_log:/var/log/supervisor
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emqx
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
  emqx_data:
  emqx_log:
  uwsgi_log:
  nginx_log:
  supervisor_log:
