version: '3'
services:
  app:
    build: .
    user: root
    ports:
      - "80:80"
      - "18083:18083"
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8084:8084"
    volumes:
      - .:/app
      - ./mqtt/emqx.conf:/etc/emqx/emqx.conf
      - ./nginx/nginx.conf:/etc/nginx/sites-available/nginx.conf
      - ./certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./certs/key.pem:/etc/ssl/certs/key.pem
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emqx
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
