version: '3'
services:
  app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emqx

  emqx:
    image: emqx/emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    depends_on:
      - postgres
