"""create user acl table

Revision ID: 84518e17df6a
Revises: 
Create Date: 2023-02-18 14:30:48.030671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84518e17df6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('ipaddress', sa.String(), nullable=False),
    sa.Column('clientid', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('permission', sa.Enum('allow', 'deny', name='permission'), nullable=True),
    sa.Column('action', sa.Enum('publish', 'subscribe', 'all', name='action'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('acl')
    # ### end Alembic commands ###
