name: Deploy production

on:
  push:
    tags:
      - v*

jobs:
  deploy-production:
    name: "Deploy production"
    runs-on: [self-hosted, linux, x64, automerge]
    container:
      image: python:3.10.10-slim-buster
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          apt-get update -y
          pip install fabric fabric2
          echo "${{ secrets.DEPLOY_KEY }}" > id_rsa
          fab deploy -H ${{ secrets.DEPLOY_HOST }} -i ./id_rsa

  verify-api:
    name: "Verify api"
    runs-on: [self-hosted, linux, x64, general]
    container:
      image: postman/newman:alpine
    needs:
      - deploy-production
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: newman run "https://api.getpostman.com/collections/${{ secrets.POSTMAN_COLLECTION_ID }}?apikey=${{ secrets.POSTMAN_API_KEY }}"

  verify-mqtt:
    name: "Verify mqtt"
    runs-on: [self-hosted, linux, x64, general]
    container: python:3.10.10
    needs:
      - deploy-production
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pip install poetry
          poetry install
      - name: Run test
        run: poetry run pytest .github/scripts/verify_mqtt_connection.py --mqtt_server ${{ secrets.MQTT_SERVER }} --mqtt_username ${{ secrets.MQTT_USERNAME }}
