name: Pull request

on: [ pull_request ]

jobs:
  flake8:
    name: "Flake8"
    runs-on: ubuntu-latest
    container: python:3.9.7-slim-buster
    steps:
      - uses: actions/checkout@v3
      - name: Install flake8
        run: pip install flake8==3.9.2 flake8-quotes==3.3.0 flake8-commas==2.0.0
      - name: Run flake8
        run: flake8 --count --show-source --statistics

  test:
    name: "Test coverage"
    runs-on: ubuntu-latest
    container: python:3.10.10
    needs:
      - flake8
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache_poetry
      - name: Run test
        run: poetry run pytest --cov
