name: Release version

on:
  push:
    branches:
      - main

concurrency:
  group: release-version-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache_poetry
      - name: Run test
        run: poetry run pytest --cov

  make-tag:
    runs-on: ubuntu-latest
    container: python:3.10-slim
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - name: Set version
        id: version-release
        run: echo "::set-output name=version::$(bash ./.github/scripts/get_version.sh)"
        env:
          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
      - uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: '${{ secrets.ERA_MQTT_AUTORELEASE_TOKEN }}'
          tag: 'v${{ steps.version-release.outputs.version }}'
