name: Release version

on:
  push:
    branches:
      - main

concurrency:
  group: release-version-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: [self-hosted, linux, x64, general]  # TODO vm
    container: python:3.10.10-slim-buster
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          apt-get update -y
          apt-get install -y build-essential python3-dev
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run test
        run: poetry run pytest --cov

  make-tag:
    runs-on: [self-hosted, linux, x64, general]
    container: python:3.10.10-slim-buster
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - name: Set version
        id: version-release
        run: echo "::set-output name=version::$(bash ./.github/scripts/get_version.sh)"
        env:
          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
      - uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: '${{ secrets.AUTORELEASE_TOKEN }}'
          tag: 'v${{ steps.version-release.outputs.version }}'
